
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/eventdb
    username: event
    password: event
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: Microservice2
server:
  port: 8082



